baseURL = 'https://bio-disks.com/'
languageCode = 'zh-cn'
title = 'Bio Disks - DNA存储技术'
disableKinds = ['taxonomy', 'term']

[params]
  description = "领先的DNA存储技术平台，为安全、高密度数据保存提供解决方案"
  author = "颜林林"
  author_url = "https://yanlinlin.cn/"
  github = "https://github.com/bio-disks"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
